spring:
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  application:
    name: sale_system
  datasource:
    url: jdbc:mysql://localhost:3306/sale_system?serverTimezone=America/Buenos_Aires&useLegacyDatetimeCode=false
    username: root
    password:
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate.ddl-auto: none
  # Gmail SMTP

  liquibase:
    change-log: classpath:/db.changelog/db.changelog-master.xml

server:
  error:
    whitelabel:
      enabled: false
    include-message: always

logging:
  level:
    org:
      springframework:
        security: INFO

